export const myData = {
  categoryList: [
    { id: 1, name: "comic" },
    { id: 2, name: "art & photography" },
    { id: 3, name: "business  " },
    { id: 4, name: "children " },
    { id: 5, name: "travel " },
  ],
  clientList: [
    {
      id: 1,
      title: "Epple",
      image: "client-1.png",
      folder: "client",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      text: "  What You Can Learn From Bill Gates",
    },
    {
      id: 2,
      title: "Epple",
      image: "client-2.png",
      folder: "client",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      text: "  What You Can Learn From Bill Gates",
    },
    {
      id: 3,
      title: "Epple",
      image: "client-3.png",
      folder: "client",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      text: "  What You Can Learn From Bill Gates",
    },
    {
      id: 4,
      title: "Epple",
      image: "client-4.png",
      folder: "client",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      text: "  What You Can Learn From Bill Gates",
    },
    {
      id: 5,
      title: "Epple",
      image: "client-5.png",
      folder: "client",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      text: "  What You Can Learn From Bill Gates",
    },
  ],
  productList: [
    {
      id: 105,
      title: "Epple 5" ,
      image: "product-4.jpg",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 1000.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: false,
      newArrivals: true,
      featuredProducts: false,
      category: 1,
      isSpecialOffer: true,
      text: "  What You Can Learn From Bill Gates",
    },
    {
      id: 104,
      title: "Epple 6",
      image: "product-4.jpg",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 5,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 25.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: false,
      newArrivals: true,
      featuredProducts: false,
      category: 1,
      isSpecialOffer: true,
      text: "  What You Can Learn From Bill Gates",
    },
    {
      id: 103,
      title: "Epple 4",
      image: "product-4.jpg",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 1,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 22.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: false,
      newArrivals: true,
      featuredProducts: false,
      category: 1,
      isSpecialOffer: true,
      text: "  What You Can Learn From Bill Gates",
    },
    {
      id: 102,
      title: "Epple 3",
      image: "product-4.jpg",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 2,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 11.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: false,
      newArrivals: true,
      featuredProducts: false,
      category: 1,
      isSpecialOffer: true,
      text: "  What You Can Learn From Bill Gates",
    },
    {
      id: 101,
      title: "Epple 7",
      image: "product-4.jpg",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 5,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 33.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: false,
      newArrivals: true,
      featuredProducts: false,
      category: 1,
      isSpecialOffer: true,
      text: "  What You Can Learn From Bill Gates",
    },
    {
      id: 100,
      title: "Epple 8",
      image: "product-4.jpg",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 4,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: false,
      newArrivals: true,
      featuredProducts: false,
      category: 1,
      isSpecialOffer: true,
      text: "  What You Can Learn From Bill Gates",
    },
    {
      id: 1,
      title: "Epple",
      image: "product-4.jpg",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: false,
      newArrivals: true,
      featuredProducts: false,
      category: 1,
      isSpecialOffer: true,
      text: "  What You Can Learn From Bill Gates",
    },
    {
      id: 2,
      title: "Hpple",
      image: "product-5.jpg",
      text: "a Half Very Simple Things You To",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: false,
      newArrivals: true,
      featuredProducts: false,
      category: 1,
      isSpecialOffer: true,
    },
    {
      id: 3,
      title: "Bpple",
      image: "product-8.jpg",
      text: "  BOOK: Do You Really Need It? This ",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: true,
      newArrivals: true,
      featuredProducts: false,
      category: 2,
      isSpecialOffer: true,
    },
    {
      id: 33,
      title: "zpple",
      image: "product-13.jpg",
      text: "BOOK: Do You Really Need It? This ",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: true,
      newArrivals: true,
      featuredProducts: false,
      category: 3,
      isSpecialOffer: true,
    },
    {
      id: 4,
      title: "Lpple",
      image: "product-2.jpg",
      text: "Revolutionize Your BOOK With ",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: true,
      newArrivals: false,
      featuredProducts: true,
      category: 3,
      isSpecialOffer: true,
    },
    {
      id: 5,
      title: "Jpple",
      image: "product-10.jpg",
      text: "Revolutionize Your BOOK With ",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: false,
      newArrivals: true,
      featuredProducts: true,
      category: 3,
      isSpecialOffer: false,
    },
    {
      id: 6,
      title: "Wpple",
      image: "product-3.jpg",
      text: "Revolutionize Your BOOK With ",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: false,
      newArrivals: true,
      featuredProducts: true,
      category: 4,
      isSpecialOffer: false,
    },
    {
      id: 7,
      title: "Hpple 2",
      image: "product-5.jpg",
      text: "a Half Very Simple Things You To",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: true,
      newArrivals: true,
      featuredProducts: false,
      category: 5,
      isSpecialOffer: false,
    },
    {
      id: 8,
      title: "Bpple 2",
      image: "product-8.jpg",
      text: "  BOOK: Do You Really Need It? This ",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: true,
      newArrivals: true,
      featuredProducts: false,
      category: 1,
      isSpecialOffer: false,
    },
    {
      id: 10,
      title: "Wpple 2",
      image: "product-3.jpg",
      text: "Revolutionize Your BOOK With ",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: true,
      newArrivals: true,
      featuredProducts: false,
      category: 5,
      isSpecialOffer: false,
    },
    {
      id: 11,
      title: "Hpple 3",
      image: "product-5.jpg",
      text: "a Half Very Simple Things You To",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: true,
      newArrivals: true,
      featuredProducts: false,
      category: 3,
      isSpecialOffer: false,
    },
    {
      id: 12,
      title: "Bpple 3",
      image: "product-8.jpg",
      text: "  BOOK: Do You Really Need It? This ",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: false,
      newArrivals: true,
      featuredProducts: true,
      category: 4,
      isSpecialOffer: false,
    },
    {
      id: 13,
      title: "Hpple 4",
      image: "product-5.jpg",
      text: "a Half Very Simple Things You To",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: true,
      newArrivals: true,
      featuredProducts: false,
      category: 3,
      isSpecialOffer: false,
    },
    {
      id: 14,
      title: "Bpple 4",
      image: "product-8.jpg",
      text: "  BOOK: Do You Really Need It? This ",
      tag: "book",
      description:
        "Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!",
      images: [
        "product-1.jpg",
        "product-2.jpg",
        "product-3.jpg",
        "product-4.jpg",
      ],
      rate: 3,
      availability: true,
      rewardPoints: "40",
      productCode: "41000",
      exTax: 41,
      brands: "Canon",
      count: 1,
      price: 51.2,
      priceOld: 51.2,
      priceDiscount: "20%",
      mostViewedProducts: false,
      newArrivals: true,
      featuredProducts: true,
      category: 3,
      isSpecialOffer: false,
    },
  ],
  carouselList: [
    {
      image: "2.jpg",
      alt: "First slide",
      interval: 10000,
      Caption: (
        <div>
          <h3>2 slide label</h3>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </div>
      ),
    },
    {
      image: "7.jpg",
      alt: "First slide",
      interval: 10000,
      Caption: (
        <div>
          <h3>7 slide label</h3>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </div>
      ),
    },
  ],
  featureList: [
    {
      id: 1,
      icon: "fas fa-truck-fast",
      h5: "Free Shipping Item",
      p: "Orders over $500",
    },
    {
      id: 2,
      icon: "fas fa-solid fa-rotate-right",
      h5: "Money Back Guarantee",
      p: "100% money back",
    },
    {
      id: 3,
      icon: "fas fa-piggy-bank",
      h5: "Cash On Delivery",
      p: "Lorem ipsum dolor amet",
    },
    {
      id: 4,
      icon: "fas fa-life-ring",
      h5: "Help & Support",
      p: "Call us : + 0123.4567.89",
    },
  ],
  reveiws: [
    {
      productId: 1,
      userId: 1,
      rate: 2,
      userName: "ADMIN",
      userImage: 1,
      dateTime: "March 23, 2015",
      text: "Lorem et placerat vestibulum, metus nisi posuere nisl, in accumsan elit odio quis mi.",
    },
  ],
};
